spring:
  application:
    name: web-service
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /resources/**
#server:
#  port: 10100
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka